[package]
name = "ir-ui"
version = "0.1.1"
edition = "2024"

[dependencies]
egui.workspace = true
egui-lucide.workspace = true
image.workspace = true
ir-app = { path = "../ir-app" }
ir-eq = { path = "../ir-eq" }
raw-window-handle.workspace = true
serde.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[dev-dependencies]
egui_extras.workspace = true
egui_kittest.workspace = true
